baseURL = "http://tallclair.netlify.com" # FIXME
languageCode = "en-us"
title = "Tim Allclair's Blog"
theme = "v1.0"
publishdir = "public"
contentdir = "content"
canonifyurls = true

[social]
twitter = "tallclair"
github = "tallclair"
stackoverflow = "1837431/tim-allclair"
email = "timsstclair@gmail.com"
