baseURL = "/"
languageCode = "en-us"
title = "Tim Allclair"
theme = "v1.0"
publishdir = "public"
contentdir = "content"
canonifyurls = true
googleAnalytics = "G-QX5GF5NDKN"

[author]
name = "Tim Allclair"

[social]
twitter = "tallclair"
github = "tallclair"
stackoverflow = "1837431/tim-allclair"
email = "timsstclair@gmail.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[markup.goldmark.renderer]
unsafe= true
