baseURL = "/"
languageCode = "en-us"
title = "Tim Allclair"
theme = "v1.0"
publishdir = "public"
contentdir = "content"
canonifyurls = true
googleAnalytics = "UA-116938249-1"

[author]
name = "Tim Allclair"

[social]
twitter = "tallclair"
github = "tallclair"
stackoverflow = "1837431/tim-allclair"
email = "timsstclair@gmail.com"
